name: Generate changelog
on:
  release:
    types: [created, edited]

  workflow_dispatch:

permissions:
  contents: write  # Set the contents permission to write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: "✏️  Generate release changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          output: "CHANGELOG.md"
          pullRequests: false
          addSections: '{"documentation":{"prefix":"**Documentation updates:**","labels":["Documentation"]}}'
          enhancementLabel: '**Implemented features and enhancements:**'
          enhancementLabels: 'enhancement,Enhancement,New Feature'
      - name: Commit changelog
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "DOC update release notes"
